[package]
name = "rust_intro"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.26.0", features = ["full"] }
axum = "0.7.4"
aide = { version = "0.13.1", features = ["axum"] }
prost = "0.13.1"
prost-types = "0.13.1"

[build-dependencies]
prost-build = "0.13.1"
